config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :rovers

  resources :grids

  root 'main#index'
end

app/models/grid.rb
class Grid < ActiveRecord::Base
end

app/models/rover.rb
class Rover < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  before_action :set_grid, only: [:show, :edit, :update, :destroy]

  # GET /grids
  # GET /grids.json
  def index
    @grids = Grid.all
  end

  # GET /grids/1
  # GET /grids/1.json
  def show
  end

  # GET /grids/new
  def new
    @grid = Grid.new
  end

  # GET /grids/1/edit
  def edit
  end

  # POST /grids
  # POST /grids.json
  def create
    @grid = Grid.new(grid_params)

    respond_to do |format|
      if @grid.save
        format.html { redirect_to @grid, notice: 'Grid was successfully created.' }
        format.json { render :show, status: :created, location: @grid }
      else
        format.html { render :new }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grids/1
  # PATCH/PUT /grids/1.json
  def update
    respond_to do |format|
      if @grid.update(grid_params)
        format.html { redirect_to @grid, notice: 'Grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @grid }
      else
        format.html { render :edit }
        format.json { render json: @grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grids/1
  # DELETE /grids/1.json
  def destroy
    @grid.destroy
    respond_to do |format|
      format.html { redirect_to grids_url, notice: 'Grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grid
      @grid = Grid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grid_params
      params.require(:grid).permit(:length, :width)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/rovers_controller.rb
class RoversController < ApplicationController
  before_action :set_rover, only: [:show, :edit, :update, :destroy]

  # GET /rovers
  # GET /rovers.json
  def index
    @rovers = Rover.all
  end

  # GET /rovers/1
  # GET /rovers/1.json
  def show
  end

  # GET /rovers/new
  def new
    @rover = Rover.new
  end

  # GET /rovers/1/edit
  def edit
  end

  # POST /rovers
  # POST /rovers.json
  def create
    @rover = Rover.new(rover_params)

    respond_to do |format|
      if @rover.save
        format.html { redirect_to @rover, notice: 'Rover was successfully created.' }
        format.json { render :show, status: :created, location: @rover }
      else
        format.html { render :new }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rovers/1
  # PATCH/PUT /rovers/1.json
  def update
    respond_to do |format|
      if @rover.update(rover_params)
        format.html { redirect_to @rover, notice: 'Rover was successfully updated.' }
        format.json { render :show, status: :ok, location: @rover }
      else
        format.html { render :edit }
        format.json { render json: @rover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rovers/1
  # DELETE /rovers/1.json
  def destroy
    @rover.destroy
    respond_to do |format|
      format.html { redirect_to rovers_url, notice: 'Rover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rover
      @rover = Rover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rover_params
      params.require(:rover).permit(:r1_start, :r1_start_direction, :r1_commands, :r2_start, :r2_start_direction, :r2_commands)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grids_helper.rb
module GridsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/rovers_helper.rb
module RoversHelper
end

app/views/grids/_form.html.erb
<%= form_for(@grid) do |f| %>
  <% if @grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grid.errors.count, "error") %> prohibited this grid from being saved:</h2>

      <ul>
      <% @grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grids/edit.html.erb
<h1>Editing grid</h1>

<%= render 'form' %>

<%= link_to 'Show', @grid %> |
<%= link_to 'Back', grids_path %>

app/views/grids/index.html.erb
<h1>Listing grids</h1>

<table>
  <thead>
    <tr>
      <th>Length</th>
      <th>Width</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grids.each do |grid| %>
      <tr>
        <td><%= grid.length %></td>
        <td><%= grid.width %></td>
        <td><%= link_to 'Show', grid %></td>
        <td><%= link_to 'Edit', edit_grid_path(grid) %></td>
        <td><%= link_to 'Destroy', grid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grid', new_grid_path %>

app/views/grids/new.html.erb
<h1>New grid</h1>

<%= render 'form' %>

<%= link_to 'Back', grids_path %>

app/views/grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @grid.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @grid.width %>
</p>

<%= link_to 'Edit', edit_grid_path(@grid) %> |
<%= link_to 'Back', grids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mars Rover</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

app/views/rovers/_form.html.erb
<%= form_for(@rover) do |f| %>
  <% if @rover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rover.errors.count, "error") %> prohibited this rover from being saved:</h2>

      <ul>
      <% @rover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :r1_start %><br>
    <%= f.number_field :r1_start %>
  </div>
  <div class="field">
    <%= f.label :r1_start_direction %><br>
    <%= f.text_field :r1_start_direction %>
  </div>
  <div class="field">
    <%= f.label :r1_commands %><br>
    <%= f.text_field :r1_commands %>
  </div>
  <div class="field">
    <%= f.label :r2_start %><br>
    <%= f.number_field :r2_start %>
  </div>
  <div class="field">
    <%= f.label :r2_start_direction %><br>
    <%= f.text_field :r2_start_direction %>
  </div>
  <div class="field">
    <%= f.label :r2_commands %><br>
    <%= f.text_field :r2_commands %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rovers/edit.html.erb
<h1>Editing rover</h1>

<%= render 'form' %>

<%= link_to 'Show', @rover %> |
<%= link_to 'Back', rovers_path %>

app/views/rovers/index.html.erb
<h1>Listing rovers</h1>

<table>
  <thead>
    <tr>
      <th>R1 start</th>
      <th>R1 start direction</th>
      <th>R1 commands</th>
      <th>R2 start</th>
      <th>R2 start direction</th>
      <th>R2 commands</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rovers.each do |rover| %>
      <tr>
        <td><%= rover.r1_start %></td>
        <td><%= rover.r1_start_direction %></td>
        <td><%= rover.r1_commands %></td>
        <td><%= rover.r2_start %></td>
        <td><%= rover.r2_start_direction %></td>
        <td><%= rover.r2_commands %></td>
        <td><%= link_to 'Show', rover %></td>
        <td><%= link_to 'Edit', edit_rover_path(rover) %></td>
        <td><%= link_to 'Destroy', rover, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rover', new_rover_path %>

app/views/rovers/new.html.erb
<h1>New rover</h1>

<%= render 'form' %>

<%= link_to 'Back', rovers_path %>

app/views/rovers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>R1 start:</strong>
  <%= @rover.r1_start %>
</p>

<p>
  <strong>R1 start direction:</strong>
  <%= @rover.r1_start_direction %>
</p>

<p>
  <strong>R1 commands:</strong>
  <%= @rover.r1_commands %>
</p>

<p>
  <strong>R2 start:</strong>
  <%= @rover.r2_start %>
</p>

<p>
  <strong>R2 start direction:</strong>
  <%= @rover.r2_start_direction %>
</p>

<p>
  <strong>R2 commands:</strong>
  <%= @rover.r2_commands %>
</p>

<%= link_to 'Edit', edit_rover_path(@rover) %> |
<%= link_to 'Back', rovers_path %>